language: node_js

node_js:
    - "16"

sudo: false

addons:
  chrome: stable

dist: xenial
services:
  - xvfb

addons:
  apt:
    sources:
      - google-chrome

git:
    submodules: false

before_script:
    - npm run build

