language: node_js

node_js:
    - "16"

sudo: false

addons:
  chrome: stable

dist: xenial
addons:
  apt:
    sources:
      - google-chrome

git:
    submodules: false

before_script:
    - "export DISPLAY=:99.0"
    - npm run build

script:
    - npm test